### ISSUE TITLE
In generated markdown, list of fields should be driven by slots, not domain/range

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#12]
E.g. in https://biolink.github.io/biolink-model/docs/BiologicalProcess.html

```
has phenotype 0..*
Description: holds between a biological entity and a phenotype, where a phenotype is construed broadly as any kind of quality of an organism part, a collection of these qualities, or a change in quality or qualities (e.g. abnormally increased temperature).
range: PhenotypicFeature
inherited from: BiologicalEntity
in subsets: (translator_minimal)
```

Should not show up

**Comment by hsolbrig** [comment]
@cmungall  - can you take a look at https://github.com/biolink/biolinkml/tree/master/tests/test_biolink_model/source/markdown to see whether this is the output that is wanted?

I haven't committed the code yet, as I've got some work to do, but I added a new slot to slot named "owner" that is set to the class name if the slot appears in class.slots and the declaring slot otherwise.  I only emit "owned" slots on class diagram.

**Comment by hsolbrig** [comment]
Fixed
