### ISSUE TITLE
missing PATO prefix

### ISSUE THREAD

**Issue by balhoff** [biolink/biolinkml#344]
Biolink model references PATO several times, but there is no PATO prefix in the context. I thought Biolink was merging in the OBO prefix set; is this not true?

**Comment by deepakunni3** [comment]
I have a fix for this. The bug is in `jsonldcontextgen.py`

**Comment by hsolbrig** [comment]
Out of curiosity -- is this a (bio)LinkML issue or a biolink-model issue?

**Comment by deepakunni3** [comment]
This was originally reported in Biolink Model. But the bug is originating from linkML.

Specifically, ContextGenerator in jsonldcontextgen.py only looks at CURIEs (and their prefixes) for the `mappings` slot of a class. It fails to check `related_mappings`, `close_mappings`, `narrow_mappings`, `exact_mappings`, and `broad_mappings`.

PR #345 adds a fix for this issue.

**Comment by cmungall** [comment]
is this now fixed?

**Comment by deepakunni3** [comment]
Yes, this was fixed almost a month ago. Should have closed the ticket when the PR #345 was merged.
